Repository Magickbase/godwoken_explorer, pull requests merged in 2022-11, with the labels that each got.

#1118 Docs: Issue 1064, add more detial description of graphql api
  docs/schema.graphql
  lib/godwoken_explorer/graphql/types/account.ex
  lib/godwoken_explorer/graphql/types/account_udt.ex
  lib/godwoken_explorer/graphql/types/block.ex
  lib/godwoken_explorer/graphql/types/common.ex
  lib/godwoken_explorer/graphql/types/log.ex
  lib/godwoken_explorer/graphql/types/polyjuice.ex
  lib/godwoken_explorer/graphql/types/smart_contract.ex
  lib/godwoken_explorer/graphql/types/sourcify.ex
  lib/godwoken_explorer/graphql/types/token_approval.ex
  lib/godwoken_explorer/graphql/types/token_instance.ex
  lib/godwoken_explorer/graphql/types/token_transfer.ex
  lib/godwoken_explorer/graphql/types/transaction.ex
  lib/godwoken_explorer/graphql/types/udt.ex
Labels: Docs

#1124 Fix: fix compile warning
  lib/godwoken_explorer/counters/accounts_counter.ex
  lib/godwoken_explorer/graphql/types/token_approval.ex
  lib/godwoken_explorer/repo.ex
  lib/godwoken_explorer/smart_contract/reader.ex
  lib/godwoken_explorer/smart_contract/solidity/publisher.ex
  lib/godwoken_explorer/smart_contract/vyper/publisher.ex
  lib/godwoken_explorer/token_approval.ex
  lib/godwoken_explorer_web/controllers/api/rpc/rpc_translator.ex
  lib/godwoken_explorer_web/router.ex
  lib/godwoken_indexer/block/pending_transaction_worker.ex
  lib/godwoken_rpc/transaction.ex
  lib/mix/tasks/update_txs_method_id_name.ex
  lib/release_tasks.ex
  mix.exs
  mix.lock
  native/molecule_parser/Cargo.lock
  native/molecule_parser/Cargo.toml
Labels: Fix

#1125 Fix: fix cursor pagination with first page not fillfull error if it has enough data
  lib/godwoken_explorer/graphql/resolovers/common.ex
  lib/godwoken_explorer/graphql/resolovers/udt.ex
  test/factories/current_udt_balance_factory.ex
  test/factories/token_transfer_factory.ex
  test/graphql/smart_contract_test.exs
  test/graphql/token_approvals_test.exs
  test/graphql/token_transfer_test.exs
  test/graphql/transaction_test.exs
  test/graphql/udt_test.exs
Labels: Fix

#1147 test: add test
  test/godwoken_explorer/account_test.exs
Labels: test

#1154 fix: filter failed polyjuice transaction
  lib/godwoken_indexer/block/sync_worker.ex
Labels: bug

#1155 feat: set timeout infinity to avoid query timeout
  lib/godwoken_explorer/block.ex
Labels: enhancement

#1143 feat: add eth_hash for polyjuice object (Issue 984)
  docs/schema.graphql
  lib/godwoken_explorer/graphql/resolovers/polyjuce.ex
  lib/godwoken_explorer/graphql/resolovers/token_transfer.ex
  lib/godwoken_explorer/graphql/resolovers/transaction.ex
  lib/godwoken_explorer/graphql/types/polyjuice.ex
  test/graphql/token_transfer_test.exs
  test/graphql/transaction_test.exs
Labels: enhancement

#1146 feat: fix null input value panic error (issue-1134)
  lib/godwoken_explorer/graphql/resolovers/udt.ex
  lib/godwoken_explorer/graphql/schemas/graphql.ex
  test/graphql/udt_test.exs
Labels: enhancement

#1167 Feat: update log/logs api with cursor-base paginator and contract subobject Issue 1140
  lib/godwoken_explorer/graphql/resolovers/log.ex
  lib/godwoken_explorer/graphql/resolovers/transaction.ex
  lib/godwoken_explorer/graphql/types/log.ex
  lib/godwoken_explorer/graphql/types/smart_contract.ex
  lib/godwoken_explorer/smart_contract.ex
  test/graphql/log_test.exs
  test/graphql/sourcify_test.exs
Labels: Feat

#1179 feat: query latest 10 transactions from transaction table
  lib/godwoken_explorer/transaction.ex
Labels: enhancement
