Repository Magickbase/godwoken_explorer, pull requests merged in 2022-12, with the labels that each got.

#1158 feat: add token exchange rate for udt (Issue-1130)
  .iex.exs
  docker_compose/gwscan_compose.yml
  lib/godwoken_explorer/chain/cache/token_exchange_rate.ex
  lib/godwoken_explorer/graphql/resolovers/token_exchange_rate.ex
  lib/godwoken_explorer/graphql/resolovers/udt.ex
  lib/godwoken_explorer/graphql/schemas/graphql.ex
  lib/godwoken_explorer/graphql/types/token_exchange_rate.ex
  lib/godwoken_explorer/graphql/types/udt.ex
  test/graphql/udt_test.exs
Labels: enhancement

#1183 Feat: add dataloader for trsanction object Issue 1114
  lib/godwoken_explorer/graphql/dataloader/graphql_ecto.ex
  lib/godwoken_explorer/graphql/resolovers/transaction.ex
  lib/godwoken_explorer/graphql/schemas/graphql.ex
  lib/godwoken_explorer/graphql/types/transaction.ex
  lib/godwoken_explorer/transaction.ex
Labels: Feat

#1185 fix: Sourcify worker duplicate job casue performance problem of pg (issue-1156)
  config/config.exs
  lib/godwoken_indexer/worker/smart_contract_register.ex
  lib/godwoken_indexer/worker/sourcify.ex
Labels: bug

#1182 chore: add udt fetcher start env
  config/runtime.exs
  docker_compose/envs/.env
  docker_compose/godwoken_explorer_compose.yml
  docker_compose/gwscan_compose.yml
  lib/godwoken_explorer/account.ex
  lib/godwoken_explorer/application.ex
  lib/godwoken_explorer/block.ex
  lib/godwoken_explorer/chain.ex
  lib/godwoken_explorer/chain/cache/block_count.ex
  lib/godwoken_explorer/exchange_rates/exchange_rates.ex
  lib/godwoken_indexer/block/sync_worker.ex
  lib/godwoken_indexer/fetcher/supervisor.ex
Labels: chore
