Repository Magickbase/godwoken_explorer, pull requests merged in 2022-10, with the labels that each got.

#1080 fix: datetime sort_by must use to compare
  lib/godwoken_explorer/account/current_udt_balance.ex
  lib/godwoken_explorer/counters/average_block_time.ex
Labels: bug

#1081 fix: datetime sort_by must use DateTime.compare/2 to compare
  lib/godwoken_explorer/account/current_udt_balance.ex
  lib/godwoken_explorer/counters/average_block_time.ex
Labels: bug

#1089 feat: create udt account before create udt
  lib/godwoken_indexer/block/sync_worker.ex
Labels: enhancement

#1099 Docs: Issue 1039 api docs
  README.md
Labels: Docs

#1103 Fix: fix call transactions with script hash input field raise error
  lib/godwoken_explorer/account.ex
  lib/godwoken_explorer/graphql/resolovers/transaction.ex
  test/graphql/transaction_test.exs
Labels: bug, Fix

#1063 Feat: add method id/name filter for txs api
  config/config.exs
  lib/godwoken_explorer/graphql/resolovers/transaction.ex
  lib/godwoken_explorer/graphql/types/transaction.ex
  lib/godwoken_explorer/polyjuice.ex
  lib/godwoken_explorer/smart_contract.ex
  lib/godwoken_explorer/transaction.ex
  lib/godwoken_indexer/block/sync_worker.ex
  lib/godwoken_indexer/worker/check_update_transaction_method_id_name.ex
  lib/mix/tasks/update_txs_method_id_name.ex
  priv/repo/migrations/20221008100002_alter_transaction_with_method_id_name.exs
  priv/repo/migrations/20221009132452_alter_transaction_with_method_id_name_index.exs
  test/graphql/transaction_test.exs
Labels: enhancement, Feat

#1100 Feat: add retry woker for erc721/erc1155 fetch name/symbol
  lib/godwoken_indexer/worker/erc1155_updater_scheduler.ex
  lib/godwoken_indexer/worker/erc721_updater_scheduler.ex
  lib/mix/tasks/fetch_erc1155_meta.ex
  lib/mix/tasks/fetch_erc721_meta.ex
Labels: Feat
